### ISSUE TITLE
Unable to resolve path to module with aliases.

### ISSUE THREAD

**Issue by sebastien-comeau** [import-js/eslint-import-resolver-typescript#359]
Starting from `tinyglobby@^0.2.11`, `eslint-import-resolver-typescript` is unable to resolve module paths when using aliases. As a workaround, I had to override `tinyglobby` to version `0.2.10` to restore functionality.  

This issue can be reproduced in my pull request https://github.com/DTS-STN/future-sir/pull/226 with commit https://github.com/DTS-STN/future-sir/commit/e1da254, where the problem occurs. The next commit https://github.com/DTS-STN/future-sir/commit/f0e3ce2 includes the override, which resolves the issue.

![Image](https://github.com/user-attachments/assets/2e8a4640-b744-44b1-9cf5-41db52d5be8f)

**Comment by carlocorradini** [comment]
That's because tinyglobby is configured to avoid dot directories.
@JounQin @SukkaW  Do you want to allow dot directories?
I don't know the implications in security/performance

**Comment by carlocorradini** [comment]
Here https://github.com/import-js/eslint-import-resolver-typescript/blob/4f47f8a604eb5cce4b21b5e10078d07e266ae88c/src/index.ts#L461 we can add `dot: true`

**Comment by JounQin** [comment]
Does this means `tinyglobby` breaks in a patch version?

**Comment by carlocorradini** [comment]
I don't know but I've seen the dot option also in version 0.2.10 if I'm not allucinated.
If it's there previously, it was silently ignored.
Tomorrow I'll push a PR with a test for both tsconfig and include property

**Comment by SuperchupuDev** [comment]
hi! tinyglobby author here. that's very odd. tinyglobby (in both 0.2.10 and 0.2.11) is configured by default to avoid dot directories, behavior shouldn't have changed between versions. so either 0.2.10 mistakenly didn't skip directories which should have been skipped or 0.2.11 somehow made dot matching (with the dot option disabled) stricter. if any of you can provide a reproducible example of results changing between the two versions i can take a closer look

**Comment by carlocorradini** [comment]
@SuperchupuDev 
1. Clone <https://github.com/carlocorradini/eslint-import-resolver-typescript>
1. `cd eslint-import-resolver-typescript`
1. `git checkout dot`
1. `yarn --immutable`
1. `yarn remove tinyglobby`
1. `yarn add tinyglobby@0.2.10`
1. Open `src/index.ts` and remove `dot: true` option from every call to `globSync` function
1. `yarn run-s build test`

There are three new tests that look for dot directories.
Let's verify if they fail or pass, even though the `dot: true` option was deleted.

**Comment by chrisweb** [comment]
As a workaround I downgraded to eslint-import-resolver-typescript **3.7.0**

> Does this means `tinyglobby` breaks in a patch version?

The latest version that supports aliases (for me) is eslint-import-resolver-typescript **3.7.0** (which was still using fast-glob), downgrading to eslint-import-resolver-typescript **3.8.2** to **3.8.0** was not enough

> tinyglobby (in both 0.2.10 and 0.2.11) is configured by default to avoid dot directories

I downgraded my tinyglobby from 0.2.11 to v0.2.10 and it made no difference

**Comment by carlocorradini** [comment]
@chrisweb See PR https://github.com/import-js/eslint-import-resolver-typescript/pull/360

It should be merged  today and a new version will be released automatically

**Comment by SuperchupuDev** [comment]
great will check it out. meanwhile if you can manage to provide a minimal isolated example that only involves one glob call it'd be greatly appreciated 🙏

**Comment by SuperchupuDev** [comment]
just to confirm that the dot directory thing is a different issue from the `..` issue that was also reported in this repo: can someone check whether this new behavior also happens with the code from SuperchupuDev/tinyglobby#91? you can test it by adding the following to your `package.json`:
```json
"overrides": {
  "tinyglobby": "https://pkg.pr.new/tinyglobby@d5fb84c"
}
```

**Comment by SuperchupuDev** [comment]
@carlocorradini while the tests do fail with 0.2.11, i added a few asserts and installing 0.2.10 at the same time to make sure the result didn't change between versions, but i can't seem to find any assert failure

**Comment by SuperchupuDev** [comment]
> I downgraded my tinyglobby from 0.2.11 to v0.2.10 and it made no difference (both break aliases when not using the dot option)

ah, so *both* versions have the issue. didn't realize. that makes my above findings make a lot more sense. i'm glad it's not a 0.2.11 regression at least? although it's really odd that this kind of test failure had gone unnoticed for so many months. if any of you can find a specific minimal repro where tinyglobby returns different results than fast-glob (as tinyglobby is meant to be a replacement to it) i can try making it consistent with fast-glob

**Comment by sebastien-comeau** [comment]
The issue has been fixed in my project. Thanks again! :)

**Comment by befabry** [comment]
Hello,

I noticed a regression from 3.7.0 to 3.8.2.

3.7.0

```dcr --rm frontend npm run lint-fix

> caddie-frontend-preact@0.0.1 lint-fix
> eslint --fix "{src,apps,libs,test}/**/*.{ts,tsx,css}"

npm notice
npm notice New major version of npm available! 10.9.2 -> 11.1.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.1.0
npm notice To update run: npm install -g npm@11.1.0
npm notice
```

However when I'm upgrading to 3.8.2

```
❯ dcr --rm frontend npm run lint-fix

> caddie-frontend-preact@0.0.1 lint-fix
> eslint --fix "{src,apps,libs,test}/**/*.{ts,tsx,css}"


/app/src/components/ui/button.tsx
  4:33  error  Unable to resolve path to module '@/lib/utils'  import-x/no-unresolved

/app/src/components/ui/form.tsx
  14:33  error  Unable to resolve path to module '@/lib/utils'  import-x/no-unresolved

/app/src/components/ui/input.tsx
  2:33  error  Unable to resolve path to module '@/lib/utils'  import-x/no-unresolved

/app/src/components/ui/label.tsx
  3:33  error  Unable to resolve path to module '@/lib/utils'  import-x/no-unresolved

/app/src/pages/AddItem/index.tsx
  4:112  error  Unable to resolve path to module '@/components/ui'  import-x/no-unresolved
  5:85   error  Unable to resolve path to module '@/helpers'        import-x/no-unresolved
  6:26   error  Unable to resolve path to module '@/hooks'          import-x/no-unresolved
  7:35   error  Unable to resolve path to module '@/messages'       import-x/no-unresolved
  8:27   error  Unable to resolve path to module '@/responses'      import-x/no-unresolved

... other errors

```

I haven't changed my config, but it doesn't seem to resolve the aliased paths. Here's (part of) my eslint config

```
// @ts-check
import eslint from '@eslint/js';
import * as tsParser from '@typescript-eslint/parser';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import eslintPluginImportX from 'eslint-plugin-import-x';
import jsxA11y from 'eslint-plugin-jsx-a11y'
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import unusedImports from 'eslint-plugin-unused-imports';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';
import tseslint, { configs as tsconfigs } from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: ['eslint.config.mjs'],
  },
  eslint.configs.recommended,
  ...tsconfigs.recommendedTypeChecked,
  react.configs.flat.recommended,
  jsxA11y.flatConfigs.recommended,
  eslintPluginImportX.flatConfigs.recommended,
  eslintPluginImportX.flatConfigs.typescript,
  eslintPluginPrettierRecommended,
  {
    plugins: {
      // react,
      //@ts-expect-error: https://github.com/facebook/react/issues/30119
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'unused-imports': unusedImports,
    },

    languageOptions: {
      globals: {
        ...globals.browser,
      },

      parser: tsParser,
      ecmaVersion: 'latest',
      sourceType: 'module',

      parserOptions: {
        project: ['tsconfig.json', 'tsconfig.app.json', 'tsconfig.node.json'],
        tsconfigRootDir: import.meta.dirname,
        ecmaFeatures: {
          jsx: true,
        },
      },
    },

    settings: {
      // https://www.npmjs.com/package/eslint-import-resolver-typescript#configuration
      'import/resolver-next': [
        createTypeScriptImportResolver({
          alwaysTryTypes: true,
          project: ['<root>/tsconfig.json', '<root>/tsconfig.app.json', '<root>/tsconfig.node.json'],
          extensions: ['.js', '.jsx', '.ts', '.tsx'],
        }),
      ],

      'import-x/ignore': [
        '\.(scss|less|css)$'
      ],

      react: {
        version: 'detect',
      },
    },

    rules: {

      // Style imports :

      // https://typescript-eslint.io/blog/consistent-type-imports-and-exports-why-and-how/
      // Consistently add inline `type` to imports & exports
      '@typescript-eslint/consistent-type-exports': ['error', { fixMixedExportsWithInlineTypeSpecifier: true }],
      '@typescript-eslint/consistent-type-imports': 'error',
      'import-x/consistent-type-specifier-style': ['error', 'prefer-inline'],
      'import-x/no-duplicates': ['error', { 'prefer-inline': true }],

      // Alphabetical order imports
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],

          pathGroups: [
            {
              pattern: '@/**',
              group: 'internal',
            },
          ],

          alphabetize: {
            order: 'asc',
            caseInsensitive: true,
          },
        },
      ],
      'sort-imports': [
        'error',
        {
          ignoreCase: true,
          ignoreDeclarationSort: true,
        },
      ],

      // Find and remove unused es6 module imports
      'unused-imports/no-unused-imports': 'error',
    },
  },
);
```

Is there something I can do to fix it ? I temporarily downgraded
